---
- name: Allow SSH in UFW
  ufw:
    rule: allow
    port: ssh
    proto: tcp
    comment: Allow ssh access

- name: limit ssh brute force
  ufw:
    rule: limit
    port: ssh
    proto: tcp
    comment: Limit ssh access

- name: Allow access to http port 80 and include a comment
  ufw:
    rule: allow
    proto: tcp
    port: http
    comment: Allow http access

- name: Allow access to https port 443 and include a comment
  ufw:
    rule: allow
    proto: tcp
    port: https
    comment: Allow https access

- name: Allow access to https port 9090 and include a comment
  ufw:
    rule: allow
    proto: tcp
    port: '9090'
    src: '147.75.33.155'
    comment: Allow rendezvous server access from benchmark machine

- name: Create a network with options
  docker_network:
    name: my-bridge
    driver_options:
      com.docker.network.bridge.name: my-bridge

- name: Allow access to http port 9000 on the host include a comment
  ufw:
    rule: allow
    proto: tcp
    port: '9000'
    direction: in
    interface: my-bridge
    comment: Allow https access

- name: Set firewall default policy
  ufw:
    state: enabled
    policy: reject
  become: yes