version: "3.2"
services:
  influxdb:
    image: influxdb:1.7-alpine
    volumes:
      - type: volume
        source: grafana
        target: /var/lib/influxdb
        volume:
          nocopy: true
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: benchmarks
  grafana:
    image: grafana/grafana:latest
    ports:
     - "3000:3000"
    volumes:
      - type: volume
        source: grafana
        target: /var/lib/grafana
        volume:
          nocopy: true
    depends_on:
      - influxdb
    links:
      - influxdb
    environment:
      GF_SERVER_ROOT_URL: http://localhost
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
  rendezvous:
    image: libp2p/websocket-star-rendezvous:release
    ports:
      - "9090:9090"
    environment:
      DISABLE_METRICS: 1
volumes:
  influx:
  grafana: